management.health.probes.enabled=true
management.endpoint.health.probes.add-additional-paths=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
management.endpoint.health.group.liveness.include=livenessState
management.endpoint.health.group.readiness.include=readinessState,db,mongo,redis,kafka
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
