spring.application.name=payment-service
server.port=${SERVER_PORT:8084}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.secret=${JWT_SECRET:Y0VyU2VjcmV0S2V5Rm9ySldUVG9rZW5TaWduaW5nMTIzNDU2Nzg5MEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFla}
gateway.internal-secret=${GATEWAY_SECRET:1$MjQ0ODc4ZTNhOGM5N2ViNDIzYmEzNDJhN2VmMjMwMzE$GYaUg+8XVS1Y0WBhM2HdGJ0Wyjneyu19mQfd9OtutWQ}

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.producer.properties.enable.idempotence=true

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.group-id=order-service-group
kafka.topics.payment-created=payment.created
kafka.topics.order-created=order.created

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){cyan} [%thread] %cyan(%logger{15}) - %msg%n
